export const AgendamentoConstantes = {
    VALOR_PROFISSIONAL_SELECIONADO: 20,
    VALOR_DESLOCAMENTO: 15,
    VALOR_DIARIA_DETALHADA: 1.9,
    VALOR_PADRAO_METRO: 2.0,
    MAX_PERCENTUAL: 15,
    PERCENTUAL_DESCONTO: 2,
    METRAGEM_MIN: 25,
    METRAGEM_MAX: 9999,
}