export enum MensagemEnum {
    CLIENTE_CRIADO_CONCLUIDO_SUCESSO = "Cliente Criado com sucesso.",
    ERRO_REAGENDAMENTO = "Houve um erro ao tentar reagendar.",
    AGENDAMENTO_CONCLUIDO_SUCESSO = "Agendamento realizado com sucesso. O seu agendamento será efetivado após o pagamento!",
    PLANO_CONCLUIDO_SUCESSO = "Plano solicitado com sucesso. O seu plano será efetivado após o pagamento!",
    PROFISSIONAIS_ATUALIZADOS_SUCESSO = "Profissionais atualizados com sucesso.",
    AGENDAMENTO_CANCELADO_SUCESSO = "Agendamento Cancelado com sucesso.",
    AGENDAMENTO_FINALIZADO_SUCESSO = "Agendamento Finalizado com sucesso.",
    PROFISSIONAL_ATUALIZADO_SUCESSO = "Profissional atualizado com sucesso.",
    REAGENDAMENTO_CONCLUIDO_SUCESSO = "Reagendamento finalizado com sucesso.",
    NECESSARIO_ATUALIZAR_PERFIL = "É necessário atualizar seu perfil para utilizar todas as funcionalidades do sistema.",
    USUARIO_NAO_AUTENTICADO = "Usuário ainda não confirmou o email. Por favor, confirme o email enviado e faça novamente o login.",
    USUARIO_CRIADO_COM_SUCESSO = "Usuário criado com sucesso.",
    EMAIL_RECUPERACAO_SENHA_ENVIADO = "O email de recuperação de senha foi enviado.",
}